/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package procedimiento;

/**
 *
 * @author Marcos Sarmientos
 */
public class Porcentajes extends javax.swing.JFrame {

    /**
     * Creates new form Porcentajes
     */
    public Porcentajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        txtPersona1 = new javax.swing.JTextField();
        txtPersona2 = new javax.swing.JTextField();
        txtPersona3 = new javax.swing.JTextField();
        txtPorcentaje1 = new javax.swing.JTextField();
        txtPorcentaje2 = new javax.swing.JTextField();
        txtPorcentaje3 = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PORCENTAJES INDIVIDUALES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setText("Persona 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setText("Persona 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jLabel4.setText("Persona 3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, 20));

        jLabel5.setText("Porcentaje");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel6.setText("Porcentaje");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel7.setText("Porcentaje");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        jLabel8.setText("Total Invertido");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        txtPersona1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPersona1KeyTyped(evt);
            }
        });
        getContentPane().add(txtPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 70, -1));

        txtPersona2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersona2ActionPerformed(evt);
            }
        });
        txtPersona2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPersona2KeyTyped(evt);
            }
        });
        getContentPane().add(txtPersona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 70, -1));

        txtPersona3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersona3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPersona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 70, -1));
        getContentPane().add(txtPorcentaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 70, -1));
        getContentPane().add(txtPorcentaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 70, -1));
        getContentPane().add(txtPorcentaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 70, -1));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPersona3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersona3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersona3ActionPerformed

    private void txtPersona2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersona2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersona2ActionPerformed

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        double suma;
       int persona1, persona2, persona3;
       double porcentaje1, porcentaje2, porcentaje3;
       String resultado1, resultado2, resultado3, total;
     

    if(txtPersona1.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this, "Digite la cantidad número Uno","error", cmdCalcular.ERROR_MESSAGE);
         txtPersona1.requestFocusInWindow();
         txtPersona1.selectAll();
//validación de vacio en persona 1
       }

     else if(txtPersona2.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite la cantidad número Dos","error", cmdCalcular.ERROR_MESSAGE);  
        txtPersona2.requestFocusInWindow();
        txtPersona2.selectAll();
//validación de vacio en persona 2
     }  
     else if(txtPersona3.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite la cantidad número tres","error", cmdCalcular.ERROR_MESSAGE);  
        txtPersona3.requestFocusInWindow(); 
         txtPersona3.selectAll();    
     }
     else{
     persona1=Integer.parseInt(txtPersona1.getText());
     persona2=Integer.parseInt(txtPersona2.getText());
     persona3=Integer.parseInt(txtPersona3.getText());     
 
   if(persona1==persona2) {
       cmdCalcular.showMessageDialog(this, "Las cantidades individuales deben ser distintas","error", cmdCalcular.ERROR_MESSAGE);  
        txtPersona1.requestFocusInWindow(); 
        txtPersona1.selectAll();  
       }  
     else if(persona2==persona3){
     cmdCalcular.showMessageDialog(this, "Las cantidades individuales deben ser distintas","error", cmdCalcular.ERROR_MESSAGE);  
        txtPersona2.requestFocusInWindow(); 
        txtPersona2.selectAll();              
       }      
     else if(persona1==persona3){
     cmdCalcular.showMessageDialog(this, "Las cantidades individuales deben ser distintas","error", cmdCalcular.ERROR_MESSAGE);  
        txtPersona1.requestFocusInWindow(); 
        txtPersona1.selectAll();              
       }     
   suma=(persona1+persona2+persona3); 
   porcentaje1=(persona1/suma)*100;
   porcentaje2=(persona2/suma)*100;
   porcentaje3=(persona3/suma)*100;

     resultado1=String.valueOf(porcentaje1);
    txtPorcentaje1.setText (resultado1);    
    
    resultado2=String.valueOf(porcentaje2);
    txtPorcentaje2.setText (resultado2);  
    
    resultado3=String.valueOf(porcentaje3);
    txtPorcentaje3.setText(resultado3); 

    total=String.valueOf(suma);
    txtTotal.setText(total);
   
   }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtTotal.setText("");
     txtPersona1.setText("");
     txtPersona2.setText("");
     txtPersona3.setText("");
     txtPorcentaje1.setText("");
     txtPorcentaje2.setText("");
     txtPorcentaje3.setText("");
     txtTotal.requestFocusInWindow();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtPersona1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPersona1KeyTyped
        char c=evt.getKeyChar(); 
       
          if(!Character.isDigit(c)) { 
              getToolkit().beep();    
              evt.consume(); 
          }
    }//GEN-LAST:event_txtPersona1KeyTyped

    private void txtPersona2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPersona2KeyTyped
        char c=evt.getKeyChar(); 
       
          if(!Character.isDigit(c)) { 
              getToolkit().beep();    
              evt.consume(); 
          }
    }//GEN-LAST:event_txtPersona2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Porcentajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Porcentajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Porcentajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Porcentajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Porcentajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtPersona1;
    private javax.swing.JTextField txtPersona2;
    private javax.swing.JTextField txtPersona3;
    private javax.swing.JTextField txtPorcentaje1;
    private javax.swing.JTextField txtPorcentaje2;
    private javax.swing.JTextField txtPorcentaje3;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
